'use client';
import {useEffect,useState} from 'react';
const ENDPOINT='https://psqxnscthiyhossgqyzn.supabase.co/functions/v1/cms-admin';
const KEY='sb_publishable_mrO_3ecMtuNLAWs7CRnJuA_RE-zynvb';
export default function AdminEdge(){
 const [secret,setSecret]=useState(''),[ok,setOk]=useState(false),[msg,setMsg]=useState(''),[tab,setTab]=useState('Dashboard');
 const [data,setData]=useState({articles:[],exhibitors:[],schedule:[],settings:[]});
 const [article,setArticle]=useState({title:'',excerpt:'',body:'',status:'draft',featured:false});const [exhibitor,setExhibitor]=useState({name:'',category:''});const [item,setItem]=useState({day:'2026-09-16',time:'09:00',title:'',description:''});
 async function call(action,payload={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({action,secret,payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha no CMS');return j}
 async function load(s=secret){try{const r=await fetch(ENDPOINT,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({action:'dashboard',secret:s,payload:{}})});const j=await r.json();if(!r.ok)throw new Error();setData(j);setOk(true);localStorage.setItem('ft_cms_key',s);setMsg('')}catch{setOk(false);setMsg('Chave administrativa inválida.')}}
 useEffect(()=>{const s=localStorage.getItem('ft_cms_key');if(s){setSecret(s);load(s)}},[]);
 async function addArticle(e){e.preventDefault();try{await call('add_article',article);setArticle({title:'',excerpt:'',body:'',status:'draft',featured:false});await load();setMsg('Matéria salva.')}catch(e){setMsg(e.message)}}
 async function addExhibitor(e){e.preventDefault();await call('add_exhibitor',exhibitor);setExhibitor({name:'',category:''});await load()}
 async function addSchedule(e){e.preventDefault();await call('add_schedule',item);setItem({day:'2026-09-16',time:'09:00',title:'',description:''});await load()}
 async function saveEvent(e){e.preventDefault();const f=new FormData(e.currentTarget);await call('update_event',{venue:f.get('venue')||'',ticket_url:f.get('ticket')||''});await load();setMsg('Configurações salvas.')}
 if(!ok)return <div className="loginWrap"><form className="loginCard" onSubmit={e=>{e.preventDefault();load()}}><img src="/logo.svg" alt="Franca Têxtil"/><h1>Painel de Controle</h1><p>Informe a chave administrativa.</p><input type="password" required value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Chave administrativa"/><button className="btn">Entrar</button>{msg&&<small>{msg}</small>}<a href="/">← Voltar ao site</a></form></div>;
 const event=data.settings?.find(x=>x.key==='event')?.value||{};const tabs=['Dashboard','Notícias','Expositores','Programação','Configurações'];
 return <main className="admin"><aside className="adminSide"><img src="/logo.svg" alt="Franca Têxtil"/><span>PAINEL DE CONTROLE</span><nav>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><a className="back" href="/">← Ver site</a><button className="textBtn" onClick={()=>{localStorage.removeItem('ft_cms_key');setOk(false)}}>Sair</button></aside><section className="adminMain"><div className="adminTop"><div><span className="eyebrow">FRANCA TÊXTIL 2026</span><h1>{tab}</h1></div><div className="status live">CMS ONLINE</div></div>{msg&&<div className="notice">{msg}</div>}
 {tab==='Dashboard'&&<div className="adminStats"><div><strong>{data.exhibitors?.length||0}</strong><span>Expositores</span></div><div><strong>{data.articles?.length||0}</strong><span>Matérias</span></div><div><strong>{data.schedule?.length||0}</strong><span>Agenda</span></div><div><strong>EDGE</strong><span>Admin seguro</span></div></div>}
 {tab==='Notícias'&&<div className="adminTwo"><form className="adminForm" onSubmit={addArticle}><h2>Nova matéria</h2><input required value={article.title} onChange={e=>setArticle({...article,title:e.target.value})} placeholder="Título"/><textarea value={article.excerpt} onChange={e=>setArticle({...article,excerpt:e.target.value})} placeholder="Resumo"/><textarea className="bodyField" value={article.body} onChange={e=>setArticle({...article,body:e.target.value})} placeholder="Texto"/><select value={article.status} onChange={e=>setArticle({...article,status:e.target.value})}><option value="draft">Rascunho</option><option value="published">Publicar agora</option></select><label><input type="checkbox" checked={article.featured} onChange={e=>setArticle({...article,featured:e.target.checked})}/> Destaque</label><button className="btn">Salvar</button></form><div className="adminList"><h2>Matérias</h2>{data.articles?.map(a=><article key={a.id}><div><b>{a.title}</b><small>{a.status}</small></div><button onClick={async()=>{await call('toggle_article',{id:a.id});await load()}}>{a.status==='published'?'Rascunho':'Publicar'}</button></article>)}</div></div>}
 {tab==='Expositores'&&<div className="adminTwo"><form className="adminForm" onSubmit={addExhibitor}><h2>Novo expositor</h2><input required value={exhibitor.name} onChange={e=>setExhibitor({...exhibitor,name:e.target.value})} placeholder="Empresa"/><input value={exhibitor.category} onChange={e=>setExhibitor({...exhibitor,category:e.target.value})} placeholder="Categoria"/><button className="btn">Adicionar</button></form><div className="adminList"><h2>Empresas</h2>{data.exhibitors?.map(x=><article key={x.id}><div><b>{x.name}</b><small>{x.active?'Ativo':'Oculto'}</small></div><button onClick={async()=>{await call('toggle_exhibitor',{id:x.id});await load()}}>{x.active?'Ocultar':'Ativar'}</button></article>)}</div></div>}
 {tab==='Programação'&&<div className="adminTwo"><form className="adminForm" onSubmit={addSchedule}><h2>Novo item</h2><input type="date" value={item.day} onChange={e=>setItem({...item,day:e.target.value})}/><input type="time" value={item.time} onChange={e=>setItem({...item,time:e.target.value})}/><input required value={item.title} onChange={e=>setItem({...item,title:e.target.value})} placeholder="Título"/><textarea value={item.description} onChange={e=>setItem({...item,description:e.target.value})} placeholder="Descrição"/><button className="btn">Adicionar</button></form><div className="adminList"><h2>Agenda</h2>{data.schedule?.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.event_day} · {(x.starts_at||'').slice(0,5)}</small></div></article>)}</div></div>}
 {tab==='Configurações'&&<form className="adminForm wide" onSubmit={saveEvent}><h2>Evento e ingressos</h2><input name="venue" defaultValue={event.venue||''} placeholder="Local do evento"/><input name="ticket" defaultValue={event.ticket_url||''} placeholder="Link oficial de ingressos"/><button className="btn">Salvar configurações</button></form>}
 </section></main>}
