const expositores=['GOL TÊXTIL','ECOMMERCE VERSO','PEDROSO TÊXTIL','BETINIS','ZANONE MALHAS','ZANONE CURSOS','ZANONE CONTÁBIL','STELLAR PRINT','MAGNA TECH','BM DO BRASIL','MAQ CENTER','MECOLOUR','HR TÊXTIL','YGUAÇU MÁQUINAS','METAL SETE','FINAL Z','FENIZ TÊXTIL','MARGIS','TW PRINT'];

const agenda=[
 ['09h00','Abertura oficial','Boas-vindas e panorama do setor têxtil'],
 ['10h00','Do produto ao digital','Como estruturar, validar e lançar produtos e marcas'],
 ['14h00','Marketplaces e varejo','Estratégias para escalar vendas online'],
 ['16h30','Cadeia produtiva e inovação','Tecnologia, maquinário e novos processos'],
 ['19h00','Conexões e negócios','Networking e oportunidades']
];

export default function Home(){return <main>
<header className="topbar"><a href="#inicio" className="brand"><img src="/logo.svg" alt="Expo Franca Têxtil Summit"/></a><nav><a href="#evento">O evento</a><a href="#programacao">Programação</a><a href="#expositores">Expositores</a><a href="#noticias">Notícias</a><a className="btn" href="#ingressos">Garanta seu ingresso</a></nav></header>
<section className="hero" id="inicio"><div className="threads"></div><div className="heroCopy"><span className="eyebrow">EXPO FRANCA TÊXTIL SUMMIT · 2026</span><h1>O MAIOR EVENTO TÊXTIL DA REGIÃO ESTÁ <em>CHEGANDO!</em></h1><p>Conexões que transformam. Conteúdo que gera resultados. Negócios que movimentam a nova economia têxtil.</p><div className="heroMeta"><b>16 E 17 DE SETEMBRO DE 2026</b><b>FRANCA / SP</b></div><div className="heroBtns"><a className="btn" href="#ingressos">Garanta seu ingresso</a><a className="btn ghost" href="#expositores">Conheça os expositores</a></div></div><div className="heroVisual"><div className="loom"></div><img src="/logo.svg" alt="Franca Têxtil"/></div></section>
<section className="stats"><div><strong>+2.000</strong><span>indústrias e empresas D2C*</span></div><div><strong>2º</strong><span>polo nacional de e-commerce D2C*</span></div><div><strong>100+</strong><span>anos de tradição produtiva*</span></div><div><strong>19</strong><span>expositores já confirmados</span></div></section>
<section id="evento" className="section"><div className="sectionHead"><div><span className="eyebrow">O EVENTO</span><h2>DO FIO <em>AO CLIQUE.</em></h2></div><p>Da matéria-prima ao consumidor final, o Summit conecta indústria, moda, tecnologia, maquinário, serviços e venda digital em um mesmo ecossistema.</p></div><div className="flow">{['Fio','Tecido','Corte','Confecção','Estamparia','Marca','E-commerce','Consumidor'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div>)}</div><div className="mediaGrid"><article className="mediaCard"><span className="eyebrow">INDÚSTRIA EM MOVIMENTO</span><h3>VEJA A INDÚSTRIA ACONTECER.</h3><p>Área preparada para vídeos de confecção, estamparia, corte e máquinas operando.</p></article><article className="mediaCard accent"><span className="eyebrow">NOVA ECONOMIA</span><h3>PRODUZIR. CONECTAR. VENDER.</h3><p>Um evento criado para encurtar caminhos entre produção, mercado e consumidor.</p></article></div></section>
<section id="expositores" className="section dark"><div className="sectionHead"><div><span className="eyebrow">ÁREA DE NEGÓCIOS</span><h2>EXPOSITORES <em>CONFIRMADOS.</em></h2></div><p>Empresas que já fazem parte da construção dessa nova cadeia têxtil em Franca e região.</p></div><div className="exGrid">{expositores.map(x=><div className="ex" key={x}>{x}</div>)}</div></section>
<section id="programacao" className="section"><div className="sectionHead"><div><span className="eyebrow">PROGRAMAÇÃO</span><h2>DOIS DIAS. <em>MUITO CONTEÚDO.</em></h2></div><p>A estrutura abaixo recebe os horários, palestrantes e salas oficiais assim que a organização fechar a programação final.</p></div><div className="schedule"><div><div className="tabs"><b>16 DE SETEMBRO</b><span>17 DE SETEMBRO</span></div>{agenda.map(([t,h,p])=><div className="slot" key={t}><time>{t}</time><div><h3>{h}</h3><p>{p}</p></div></div>)}</div><aside className="poster"><img src="/logo.svg" alt="Expo Franca Têxtil Summit"/><strong>16 E 17</strong><b>SETEMBRO</b><span>2026 · FRANCA/SP</span></aside></div></section>
<section id="noticias" className="section dark"><div className="sectionHead"><div><span className="eyebrow">NOTÍCIAS</span><h2>O SETOR JÁ COMEÇOU A <em>SE MOVIMENTAR.</em></h2></div><p>Conteúdo editorial para explicar a transformação econômica e ampliar a presença digital do evento.</p></div><article className="featured"><div><span className="tag">DESTAQUE</span><h3>Franca Têxtil Summit 2026 quer transformar a cidade em vitrine da nova economia têxtil</h3><p>O evento nasce no encontro entre tradição produtiva, empreendedorismo, tecnologia e venda direta ao consumidor.</p><a className="btn" target="_blank" href="https://amofranca.com/materia/franca-textil-summit-2026-quer-transformar-a-cidade-em-vitrine-da-nova-economia-textil">Ler matéria completa</a></div></article></section>
<section id="ingressos" className="ctaBand"><div><span className="eyebrow">INGRESSOS</span><h2>GARANTA SEU LUGAR E FAÇA PARTE DO FUTURO TÊXTIL.</h2><p>O link oficial de compra entra aqui assim que for confirmado.</p></div><a className="btn darkBtn" href="#">Garanta seu ingresso</a></section>
<footer><img src="/logo.svg" alt="Expo Franca Têxtil"/><div><b>16 E 17 DE SETEMBRO DE 2026</b><p>Franca · São Paulo · Brasil</p><small>*Dados do material-base do evento sujeitos a validação da organização.</small></div><a href="/admin">Acesso administrativo</a></footer>
</main>}
